### ISSUE TITLE
프로그램 목적 및 기능

### ISSUE THREAD

**Issue by cplife7816** [HGUBabgo/BabGo#1]
사용자에게서 시간을 입력 받아 
다른 사용자와의 시간을 비교 적절한 밥고 시간을 찾아주는 기능

**Comment by yneun** [comment]
저희 밥고 시간이랑 팀플시간 찾아주는 기능으로 확장하면서 세분화하면 어떨까요?

**Comment by cplife7816** [comment]
그러면 밥고 비교를 할때는 교시로 팀플 비교를 할때는 시간으로 하는건 어떨까요?

**Comment by yneun** [comment]
괜찮은 것 같아요!
