### ISSUE TITLE
사용할 데이터 형태 

### ISSUE THREAD

**Issue by cplife7816** [HGUBabgo/BabGo#2]
사용자의 이름 char name [20] 
월~금 교시 
int mon [10] 
int tue [10] 
int wed [10] 
int thr [10] 
int fri [10]
int sat[10]
int sun[10]

(수정)토,일 추가 완료 했습니다.

**Comment by yneun** [comment]
만약을 위해 토요일과 일요일도 추가하면 어떨까요?

**Comment by yneun** [comment]
목적에 따른 항목 추가
char name [20]
int type
int mon [10]
int tue [10]
int wed [10]
int thr [10]
int fri [10]
int sat[10]
int sun[10]
