### ISSUE TITLE
구조체 정의

### ISSUE THREAD

**Issue by yneun** [HGUBabgo/BabGo#3]
구조체 정의를 위해 어떠한 데이터들이 필요한까요?
일단 밥고랑 팀플을 따로 구분해서 정의할까요?

**Comment by cplife7816** [comment]
우선 사용자의 이름 그리고 요일 별 시간들을 추가하면 될 것 같네요. 시간은 교시로 통일하여 밥고랑 팀플 시간을 구하는 것도 나쁘지 않을 것 같네요
제가 생각한 예시는  
typedef struct 
{
char namer [30]
int sun [20]
int mon [20]
int tue [20]
int wed [20]
int thu [20]
int fri [20]
int sat [20]
} time;
입니다.

**Comment by yneun** [comment]
제가 생각한것은 팀플이랑 밥고를 구별하기 위해 하나의 항목을 추가하는 건데요.
typedef struct {
char name [30]
int type
int sun [20]
int mon [20]
int tue [20]
int wed [20]
int thu [20]
int fri [20]
int sat [20]
} Time;
이렇게 하여서 예를 들면 type의 데이터가 1이면 팀플, 2면 밥고 이렇게 생각해봤어요.

**Comment by cplife7816** [comment]
좋은 생각이네요
혹시 그럼 밥고랑 팀플이랑 시간 개념을 다르게 하는게 좋을까요? 그렇게 되면 비교 할 때 함수의 기능을 두개로 나누어야 할 것 같아요...

**Comment by yneun** [comment]
아니면 교시말고 시(예를 들면 12시면 12, 1시면 13시)로 통합할까요?

**Comment by cplife7816** [comment]
통합하는게 좋을 것 같아요. 그렇게 되면 시간 비교 함수를 하나만 만들어도 될 것 같아요
이렇게 되면 밥고나 팀플이나 딱히 상관이 없을 것 같네요
차이가 있다면 밥고는 아침 점심 저녁 시간대만 비교하는 정도?

**Comment by yneun** [comment]
일단 밥고나 팀플을 설정하는 이유는 같은 목적을 가진 사람들만 모아서 비교하기 위해서이니까 비교함수는 하나이되, 함수부분에서 원하는 목적을(팀플/밥고) 입력받고 비교하는 부분을 고려하게 할 수 있을것 같아요.

**Comment by cplife7816** [comment]
그러면 데이터 비교 함수를 목적(밥고/팀플)에 따라 다르게 비교하는 함수로 만들면 될 것 같네요. 
1(밥고) 일때와 2(팀플) 일때 찾아주는 시간대를 조정하면 될 것 같아요.

**Comment by yneun** [comment]
그럼 함수부분 issue에서 해당 사항을 추가할께요!
