### ISSUE TITLE
입력할 데이터의 형태 입력 방식

### ISSUE THREAD

**Issue by cplife7816** [HGUBabgo/BabGo#5]
사용자 이름은 ? 
밥고 : 1 / 팀플 : 2
(띄어쓰기로 시간 표시 EX) 2 3 4)
월요일 시간은 ? 
화요일 시간은 ? 
수요일 시간은 ? 
목요일 시간은 ? 
금요일 시간은 ? 
토요일 시간은 ? 
일요일 시간은 ? 

이런 입력문으로 하는 건 어떨까요?

**Comment by yneun** [comment]
좋아요!
저희가 출력할 문장을

사용자 이름은?
원하는 기능은? (밥고 : 1, 팀플 : 2)
월요일에 가능한 시간은?

이렇게 할까요?

**Comment by cplife7816** [comment]
좋습니다~ 월요일에 가능한 시간 위에 사용자에게 어떤 형식으로 시간을 입력하는 것인지 만 추가하면 더욱 유용 할것 같아요~
예를 들어서 
(데이터 입력 ex) 2 3 4 )
같은 것을 올리는 거죠

**Comment by yneun** [comment]
네네 그럼 시간은 가능한 시간대로 하죠!

**Comment by cplife7816** [comment]
가능한 시간대로 설정하려면 가장 일반적인 아침 8시부터 저녁 12시까지 즉 8 ~ 24시 까지만 받도록 할까요?
여기에 대한 범위를 설정해야 데이터 처리가 편할 것 같아요

**Comment by yneun** [comment]
한동대를 기준으로 할때 7~24시가 낫지 않을까요?
1교시가 8시30이라...

**Comment by cplife7816** [comment]
그러면 7시부터 24시까지 데이터를 입력 받도록 할게요.

**Comment by yneun** [comment]
네!
